

services:
  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\Admin\Documents\projekt\scraper\data\postgis\data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      volumes:
        - C:\Users\Admin\Documents\projekt\scraper\data\postgis\pgadmin:/var/lib/pgadmin
      depends_on:
        - postgis
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    volumes:
      - "C:/Users/Admin/Documents/projekt/scraper/data/rabbitmq:/var/lib/rabbitmq"
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  scraper:
    container_name: scraper
    build:
      context: ..
      dockerfile: docker/dockerfiles/scraper.dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

  processor:
    container_name: processor
    build:
      context: ..
      dockerfile: docker/dockerfiles/processor.dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ../logs:/app/logs
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq

  backend:
      container_name: backend
      build:
        context: ..
        dockerfile: docker/dockerfiles/backend.dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ../backend:/app/backend
        - ../frontEnd/dist/frontEnd/browser:/app/frontEnd/dist/frontEnd/browser
      environment:
        DATABASE_URL: postgresql://postgres:postgres@postgis:5432/gis
      stdin_open: true
      tty: true
      depends_on:
        - postgis